var workSeqStart = 87;
var workSeqEnd = 89;
var workSeqExcep = [96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 85, 84, 83, 82]; /* DesignTemplate */

var workLiSimple = [
	{ 'seq': '45', 'subject': 'KT CLiP CARD', 'hashtag': ['sm', 'app'] },
	{ 'seq': '44', 'subject': 'KT CLiP 앱 3.0 리뉴얼', 'hashtag': ['si', 'app'] },
	{ 'seq': '43', 'subject': 'KT 사용자 요금제 역경매 프로젝트 디자인', 'hashtag': ['sm', 'web'] },
	{ 'seq': '42', 'subject': 'KT 스마트 APP 명세서 디자인', 'hashtag': ['sm', 'app'] },
	{ 'seq': '41', 'subject': '롯데 e-커머스 백오피스 통합 플랫폼 구축 참여', 'hashtag': ['si', 'web'] },
	{ 'seq': '40', 'subject': '라이나생명 하트히어로 앱 신규 구축', 'hashtag': ['si', 'app'] },
	{ 'seq': '39', 'subject': 'KT 100C 신규 구축', 'hashtag': ['si', 'web'] },
	{ 'seq': '38', 'subject': '롯데호텔 IR 사이트 신규 홈페이지 구축', 'hashtag': ['si', 'web'] },
	{ 'seq': '37', 'subject': '삼성물산 패션부문 Brand몰 구축(토리버치, 톰브라운)', 'hashtag': ['si', 'web'] },
	{ 'seq': '36', 'subject': '롯데재단 웹/모바일 사이트 개선 및 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '35', 'subject': '롯데인터넷면세점 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '34', 'subject': '롯데인터넷면세점 샤넬 전용관 추가', 'hashtag': ['si', 'web'] },
	{ 'seq': '33', 'subject': '롯데인터넷면세점 VIP CLUB 스마트쿠폰북', 'hashtag': ['si', 'web'] },
	{ 'seq': '32', 'subject': '롯데인터넷면세점 웹/모바일/어드민 개선', 'hashtag': ['si', 'web'] },
	{ 'seq': '31', 'subject': '롯데칠성몰 웹사이트 리뉴얼 구축', 'hashtag': ['si', 'web'] },
	{ 'seq': '30', 'subject': '롯데에비뉴엘 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '29', 'subject': '롯데백화점 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '28', 'subject': '롯데몰 김포공항점 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '27', 'subject': '롯데몰 수원점 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '26', 'subject': '롯데재단 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '25', 'subject': '롯데칠성몰 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '24', 'subject': '롯데그룹', 'hashtag': ['sm', 'web'] },
	{ 'seq': '23', 'subject': '롯데멤버스', 'hashtag': ['sm', 'web'] },
	{ 'seq': '22', 'subject': '롯데백화점 엘룩 뷰어 UI 개선', 'hashtag': ['si', 'web'] },
	{ 'seq': '21', 'subject': '롯데피트인 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '20', 'subject': '롯데피트인 동대문 쇼핑몰 사이트 오픈', 'hashtag': ['si', 'web'] },
	{ 'seq': '19', 'subject': '롯데 IR 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '18', 'subject': '롯데백화점 상품본부 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '17', 'subject': '롯데 IR 웹사이트 리뉴얼 오픈', 'hashtag': ['si', 'web'] },
	{ 'seq': '16', 'subject': '메리츠화재 웹 접근성 개선 오픈', 'hashtag': ['sm', 'web'] },
	{ 'seq': '15', 'subject': '하나생명', 'hashtag': ['sm', 'web'] },
	{ 'seq': '14', 'subject': '롯데백화점 아울렛 웹접근성 구축', 'hashtag': ['si', 'web'] },
	{ 'seq': '13', 'subject': '롯데상품본부 웹사이트 리뉴얼 오픈', 'hashtag': ['si', 'web'] },
	{ 'seq': '12', 'subject': '롯데타운', 'hashtag': ['sm', 'web'] },
	{ 'seq': '11', 'subject': '법무법인 백상 웹사이트 신규 오픈', 'hashtag': ['si', 'web'] },
	{ 'seq': '10', 'subject': '롯데백화점 홍보관 운영', 'hashtag': ['sm', 'web'] },
	{ 'seq': '09', 'subject': '몽당서림 프로모션 오픈', 'hashtag': ['si', 'web'] },
	{ 'seq': '08', 'subject': 'T-STORE 체인지마우스 APP제작 오픈', 'hashtag': ['si', 'app'] },
	{ 'seq': '07', 'subject': 'T-STORE 링링 APP 제작 ', 'hashtag': ['si', 'app'] },
	{ 'seq': '06', 'subject': '롯데쇼핑 30년사 사이버 전시관 ', 'hashtag': ['si', 'web'] },
	{ 'seq': '05', 'subject': '롯데성주 스카이힐 사이트 제작', 'hashtag': ['si', 'web'] },
	{ 'seq': '04', 'subject': '롯데부산인터넷면세점 구축', 'hashtag': ['si', 'web'] },
	{ 'seq': '03', 'subject': '롯데백화점 ECO전단 뷰어 제작', 'hashtag': ['si', 'web'] },
	{ 'seq': '02', 'subject': '유타몰 사이트 구축', 'hashtag': ['si', 'web'] },
	{ 'seq': '01', 'subject': '토이저러스 사이트 구축', 'hashtag': ['si', 'web'] }
];